// generated by Fast Light User Interface Designer (fluid) version 1.0304
//DEFININDO VARIAVEIS DA GUI APOS IMPORTAR SUA BIBLIOTECA RESPECTIVA
#ifndef gui_h
#define gui_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *janela;
#include <FL/Fl_Text_Display.H>
extern Fl_Text_Display *mensagens;
#include <FL/Fl_Input.H>
extern Fl_Input *ipServ;
extern Fl_Input *username;
extern Fl_Input *escrita;
#include <Fl/Fl_Text_Buffer.H>
extern Fl_Text_Buffer *buffer;
#include <FL/Fl_Return_Button.H>
extern Fl_Return_Button *startChat;
extern Fl_Return_Button *bEnviar;
extern Fl_Input *nick;
extern Fl_Return_Button *bNick;
extern Fl_Input *kick;
extern Fl_Return_Button *bKick;
extern Fl_Input *mute;
extern Fl_Return_Button *bMute;
extern Fl_Input *unmute;
extern Fl_Return_Button *bUnmute;
extern Fl_Input *whois;
extern Fl_Return_Button *bWhois;
extern "C" { Fl_Double_Window* make_window(); }
#endif
